package com.messenger.app.data.repository

import android.util.Log
import com.messenger.app.data.encryption.history.HistoryArchiveDisabledException
import com.messenger.app.data.encryption.history.HistoryArchiveFeature
import com.messenger.app.data.encryption.history.HistoryCrypto
import com.messenger.app.data.encryption.history.HistoryKeyring
import com.messenger.app.data.encryption.history.HistoryKeyringCacheFormat
import com.messenger.app.data.encryption.history.HistoryKeyringMerge
import com.messenger.app.data.encryption.history.HistoryKeyringStore
import com.messenger.app.data.encryption.history.HistoryKeyringVault
import com.messenger.app.data.encryption.history.HistoryRootEntry
import com.messenger.app.data.encryption.history.HistoryUserProvider
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Owns the per-chat archive roots (Layer B).
 *
 * The keyring is held sealed at rest and opened through the vault, so the roots exist in the clear
 * only inside this process. Every write goes seal-then-store: if either half fails, nothing is
 * persisted and the in-memory cache is left untouched, so the caller can never proceed believing a
 * root is durable when it is not.
 *
 * This class deliberately holds no Android, MLS, Room, or network dependency - it talks only to the
 * two ports - which keeps the entire policy JVM-testable. The rules it enforces are the ones that
 * are easy to get wrong:
 *
 *  - an unreadable keyring is a failure, never an empty one (see [HistoryKeyringStore]);
 *  - a root is returned only after it is durably stored;
 *  - rotation adds a version, never replaces one, because older archives still need their old root.
 *
 * Nothing here derives from, or feeds into, MLS. Roots are generated by [HistoryCrypto.newHistoryRoot].
 */
@Singleton
class HistoryKeyringRepository @Inject constructor(
    private val vault: HistoryKeyringVault,
    private val store: HistoryKeyringStore,
    /**
     * The signed-in account. The Keystore cache is bound to it; without an
     * identity no cached roots may be accepted. See [HistoryKeyringCacheFormat].
     */
    private val users: HistoryUserProvider,
    /**
     * The containment boundary, enforced at the MUTATION points rather than at any
     * one caller. Rotation reaches this class from live ViewModels without passing
     * through MessageArchiver, so a flag checked only in the archiver let a
     * disabled feature mint and durably persist roots.
     */
    private val feature: HistoryArchiveFeature,
) {

    private companion object {
        const val TAG = "HistoryKeyring"
    }

    private val mutex = Mutex()

    /** Opened keyring for this process. Null means "not loaded yet", never "known empty". */
    @Volatile
    private var cached: HistoryKeyring? = null

    /**
     * The account [cached] was opened for.
     *
     * The in-memory copy is plaintext roots, and it is consulted before anything
     * else on the read path - so if the signed-in account changes while this
     * object survives, the previous account's history would be handed to the new
     * one. Logout does clear it, but relying on a lifecycle call being made is a
     * weaker guarantee than checking: this makes the separation structural, so it
     * holds even on a path that reaches a second account without a logout.
     *
     * The durable copies are unaffected either way - the authoritative blob is
     * AAD-bound and the cache is owner-bound. This closes the one copy that has
     * no binding of its own.
     */
    private var cachedOwner: String? = null

    /**
     * Chats where a security boundary was crossed but the rotation has not yet succeeded.
     *
     * This is the barrier that makes rotation a real security event rather than a hint. While a
     * chat is listed here [ensureRoot] refuses, so nothing can be archived under the root that the
     * security event just invalidated. A failed rotation therefore costs archiving for that chat -
     * it does not silently fall back to the old root.
     *
     * Guarded by [mutex] like the rest of this class.
     */
    private val rotationRequired = mutableSetOf<String>()

    /**
     * Bumped on every durable keyring change.
     *
     * Exists so the recovery upload can be driven from OUTSIDE this class's lock.
     * Network I/O must never happen while the keyring mutex is held, so callers
     * compare this cheap counter after a mutation returns and upload only when it
     * moved. Every durable change funnels through [persistLocked], so one counter
     * covers minting, rotation, and recovery import alike.
     */
    @Volatile
    private var revision: Long = 0

    /** Current keyring revision; changes iff the durable keyring changed. */
    fun currentRevision(): Long = revision

    /**
     * The current keyring, opening it from local storage on first use.
     *
     * A device that has never archived anything legitimately has no stored keyring; that is
     * success(empty). A keyring that is stored but cannot be opened is a failure - reporting it as
     * empty would silently orphan every existing archive.
     */
    suspend fun load(): Result<HistoryKeyring> = mutex.withLock { loadLocked() }

    /**
     * Two-copy load.
     *
     * The Keystore cache is tried first because it is the only copy readable without an unlocked
     * vault - that is what lets an ordinary restart show archived history with no password prompt.
     * The MK-sealed copy is the source of truth and the fallback.
     *
     * The full outcome matrix, all of it fail-closed:
     *
     *     cache ok/bytes                       -> use it, no vault needed
     *     cache ok/null  + auth ok/null        -> genuinely fresh device, empty keyring
     *     cache ok/null  + auth ok/bytes       -> recover through the vault, refresh the cache
     *     cache fails    + auth ok/bytes       -> recover through the vault, refresh the cache
     *     cache fails    + auth ok/null        -> FAILURE (cannot tell "fresh" from "broken")
     *     anything       + vault locked        -> FAILURE
     *
     * The one case that must never be reached is "return an empty keyring because something went
     * wrong", because the caller would then mint a fresh root over the top of live archives.
     */
    private suspend fun loadLocked(): Result<HistoryKeyring> {
        val owner = runCatching { users.currentUserId() }.getOrNull()

        // Identity first. An in-memory keyring belongs to the account it was
        // opened for and to no other.
        if (cached != null && cachedOwner != owner) {
            Log.w(TAG, "signed-in account changed; dropping the in-memory history keyring")
            cached = null
            cachedOwner = null
        }
        cached?.let { return Result.success(it) }

        val cacheRead = store.loadHistoryKeyringCache()
        val cacheBytes = cacheRead.getOrNull()

        // The cache is account-bound. Three outcomes, and the difference between
        // the last two is the whole point:
        //
        //   Owned          -> ours, use it
        //   ForAnotherUser -> provably NOT ours, so it is exactly as good as no
        //                     cache: there is no history of ours to orphan, and
        //                     a fresh keyring is correct
        //   Unusable       -> legacy/corrupt/unidentifiable, ownership UNKNOWN.
        //                     Starting fresh could orphan archives this account
        //                     already wrote, so it must not be treated as absent.
        val decodedCache = HistoryKeyringCacheFormat.decode(cacheBytes, owner)
        val cacheIsForeign = decodedCache is HistoryKeyringCacheFormat.Decoded.ForAnotherUser

        // FRESHNESS. The cache is the only copy readable without MK, so a cold
        // start reads it first - which is precisely why it must not be trusted on
        // structure and ownership alone. The marker is bumped before the
        // authoritative write and stamped into the cache only after both writes
        // land, so a stamp equal to the marker is the one piece of evidence that
        // this cache was built from the current authoritative state.
        //
        // A mismatch is not corruption and not foreign ownership: it means a
        // write was interrupted. The response is to fall through to the
        // authoritative copy, which then re-stamps the cache below.
        val marker = store.loadHistoryKeyringGeneration().getOrNull()
        if (decodedCache is HistoryKeyringCacheFormat.Decoded.Owned) {
            if (marker != null && decodedCache.generation == marker) {
                val decoded = decodeAndCache(decodedCache.keyringBytes)
                if (decoded.isSuccess) return decoded
                // Our own current cache, but the payload is damaged. The
                // authoritative copy may still be good; fall through, and never
                // fall through to "empty".
            } else {
                Log.w(
                    TAG,
                    "history keyring cache is not known to match the authoritative copy " +
                        "(stamp=${decodedCache.generation}, marker=$marker); reading through the vault"
                )
            }
        }

        val stored = store.loadHistoryKeyring().getOrElse { return Result.failure(it) }
        if (stored == null) {
            // Absent cache, or a cache that demonstrably belongs to someone else.
            // Note the condition is unchanged in meaning: only a genuinely absent
            // cache or a provably foreign one may become an empty keyring. A stale
            // Owned cache is neither, so it still refuses rather than minting.
            return if (cacheRead.isSuccess && (cacheBytes == null || cacheIsForeign)) {
                // Both copies genuinely absent: a device that has never archived anything.
                HistoryKeyring.of(emptyList()).onSuccess { rememberOpened(it) }
            } else {
                // The cache was unreadable and there is no authoritative copy to arbitrate with.
                // Minting a new keyring here is exactly the mistake this whole class exists to
                // prevent, so refuse.
                Result.failure(
                    IllegalStateException(
                        "history keyring cache is unreadable and no recovery copy exists; " +
                            "refusing to mint a replacement keyring"
                    )
                )
            }
        }

        val plain = vault.openHistoryKeyring(stored).getOrElse { openFailure ->
            // The authoritative copy would not open. That is normally fatal - it
            // may be OUR keyring, damaged - so it fails closed.
            //
            // The one exception is when the cache proved the stored state belongs
            // to a DIFFERENT account. An MK-sealed blob cannot say whose it is:
            // a wrong-account blob and a corrupt one both surface as the same
            // authentication failure. The account-bound cache supplies exactly the
            // evidence the sealed blob lacks, and with it "this device's keyring
            // belongs to someone else" is a sound conclusion. Starting fresh then
            // orphans nothing of THIS account's, because this account has never
            // written a keyring here.
            //
            // Without that evidence this stays a failure. Same user, own cache:
            // the cache is Owned or absent, never foreign, so this branch is
            // unreachable for a user whose own archives exist.
            if (cacheIsForeign) {
                return HistoryKeyring.of(emptyList()).onSuccess { rememberOpened(it) }
            }
            return Result.failure(openFailure)
        }
        return try {
            decodeAndCache(plain).onSuccess {
                // Recovered through the vault, so the vault is unlocked: this is the reconcile
                // point named in the cold-start decision. A cache that cannot be refreshed is
                // removed rather than left stale - see [writeCache].
                //
                // Stamping with the CURRENT marker is what repairs an interrupted
                // write: the cache now provably matches the authoritative copy it
                // was just built from, so the next cold start can use it again.
                // Every successful vault read therefore reconciles. That is the
                // ONLY reconciliation path there is: a separate repair entry point
                // used to exist, was never called from production, and was itself
                // an ungated mutation - so it is gone rather than left as a second
                // way to write the same two slots.
                //
                // A device that already held a keyring before this format existed
                // has no marker at all. Stamping such a cache with a value that is
                // not durably recorded would leave it permanently mismatched, so
                // the marker is established here - once - and the cache is stamped
                // to match it.
                writeCache(plain, ensureMarkerLocked(marker))
            }
        } finally {
            HistoryCrypto.bestEffortWipe(plain)
        }
    }

    private suspend fun decodeAndCache(plain: ByteArray): Result<HistoryKeyring> =
        HistoryKeyring.decode(plain).onSuccess { rememberOpened(it) }

    /** Records the opened keyring together with the account it belongs to. */
    private suspend fun rememberOpened(keyring: HistoryKeyring) {
        cached = keyring
        cachedOwner = runCatching { users.currentUserId() }.getOrNull()
    }

    /**
     * Writes the cache, and on failure removes it instead of leaving it behind.
     *
     * A stale cache is worse than no cache: it is preferred over the authoritative copy on the next
     * cold start, so it would serve outdated roots and make newly archived messages unopenable. If
     * even the removal fails, that is a genuine failure - the caller must not believe the keyring
     * is consistent.
     */
    /**
     * Returns the current marker, creating one if this device predates the format.
     *
     * Only ever moves forward. A marker that fails to persist is reported as 0,
     * which simply leaves the cache mismatched and forces the next read through
     * the vault again - the safe direction.
     */
    private suspend fun ensureMarkerLocked(current: Long?): Long {
        if (current != null) return current
        val seeded = 1L
        return store.saveHistoryKeyringGeneration(seeded).fold(
            onSuccess = { seeded },
            onFailure = {
                Log.w(TAG, "could not establish a history keyring generation marker: ${it.message}")
                0L
            }
        )
    }

    private suspend fun writeCache(plain: ByteArray, generation: Long): Result<Unit> {
        // Bind the cache to the signed-in account. Without an identity there is
        // nothing to bind to, so no cache is written at all - the authoritative
        // MK-sealed copy is already durable, and an unbound cache is precisely
        // what this change exists to eliminate.
        val owner = runCatching { users.currentUserId() }.getOrNull()
        if (owner.isNullOrBlank()) {
            return store.deleteHistoryKeyringCache().fold(
                onSuccess = { Result.success(Unit) },
                onFailure = {
                    Result.failure(
                        IllegalStateException(
                            "no signed-in account to bind the history keyring cache to, " +
                                "and the existing cache could not be removed",
                            it
                        )
                    )
                }
            )
        }
        val bound = HistoryKeyringCacheFormat.encode(owner, generation, plain)
        store.saveHistoryKeyringCache(bound).onSuccess { return Result.success(Unit) }
        return store.deleteHistoryKeyringCache().fold(
            onSuccess = { Result.success(Unit) },
            onFailure = {
                Result.failure(
                    IllegalStateException(
                        "history keyring cache could not be refreshed or removed; " +
                            "a stale cache would serve outdated roots",
                        it
                    )
                )
            }
        )
    }

    /**
     * The newest root for [chatId], minting one on first use.
     *
     * The new root is returned only once it has been sealed and stored. Handing back a root that
     * failed to persist would let messages be archived under a key that no restart can recover.
     */
    suspend fun ensureRoot(chatId: String): Result<HistoryRootEntry> = mutex.withLock {
        if (!feature.isEnabled()) return Result.failure(HistoryArchiveDisabledException())
        require(chatId.isNotEmpty()) { "chatId must not be empty" }
        if (chatId in rotationRequired) {
            // A security boundary was crossed and the rotation has not landed. Handing back the old
            // root here would archive post-event messages under a key the event was meant to
            // retire, which is exactly what rotation exists to prevent.
            return Result.failure(
                IllegalStateException(
                    "history root for this chat must rotate after a security event before " +
                        "anything else may be archived"
                )
            )
        }
        val keyring = loadLocked().getOrElse { return Result.failure(it) }
        keyring.latest(chatId)?.let { return Result.success(it) }
        addVersionLocked(keyring, chatId, version = 1)
    }

    /**
     * Raises the barrier for [chatId]: archiving is refused until a rotation succeeds.
     *
     * Called before attempting rotation, so a crash or failure between the two leaves the chat
     * closed rather than open. Safe to call repeatedly.
     */
    suspend fun markRotationRequired(chatId: String) = mutex.withLock {
        // A barrier raised for a disabled feature is state mutation too, and it
        // would still be standing if the flag were later turned on.
        if (!feature.isEnabled()) return@withLock Unit
        if (chatId.isNotBlank()) rotationRequired.add(chatId)
        Unit
    }

    /** Whether archiving is currently blocked for [chatId] pending a rotation. */
    suspend fun isRotationRequired(chatId: String): Boolean = mutex.withLock {
        chatId in rotationRequired
    }

    /**
     * Starts a new root version for [chatId], keeping every earlier version.
     *
     * Rotation limits what a newly rotated-out party can read GOING FORWARD. It does not and cannot
     * retroactively protect history already archived under an earlier root, and it does not erase
     * anything a device already holds - do not describe it as forward secrecy for past messages.
     */
    suspend fun rotate(chatId: String): Result<HistoryRootEntry> = mutex.withLock {
        // Rotation reaches this class straight from ViewModels, never through
        // MessageArchiver, so this is the only place the guard actually contains
        // it. Without it an ordinary security event mints and persists a root
        // while the feature is switched off.
        if (!feature.isEnabled()) return Result.failure(HistoryArchiveDisabledException())
        require(chatId.isNotEmpty()) { "chatId must not be empty" }
        val keyring = loadLocked().getOrElse { return Result.failure(it) }
        val next = (keyring.latest(chatId)?.rootVersion ?: 0) + 1
        addVersionLocked(keyring, chatId, next).onSuccess {
            // Only a durably persisted new root lifts the barrier.
            rotationRequired.remove(chatId)
        }
    }

    /**
     * The authoritative keyring, serialised for recovery upload.
     *
     * Returns the same encoding the local copies use. Fails if the keyring cannot
     * be read - a locked vault or unreadable storage must never produce an empty
     * upload, which would look like "this account has no roots" and could later
     * be merged over a device that does.
     */
    suspend fun exportForRecovery(): Result<ByteArray> = mutex.withLock {
        loadLocked().map { it.encode() }
    }

    /** Encoded keyring plus the revision it was taken at. */
    data class RecoveryExport(val bytes: ByteArray, val revision: Long)

    /**
     * [exportForRecovery] with the revision captured under the SAME lock.
     *
     * Reading the revision separately - before or after - names a state that may
     * not be the one encoded here, and the publisher uses this value to decide
     * what has been sent. Taking both inside one critical section makes the
     * answer exact instead of merely conservative, which is what keeps a mutation
     * landing mid-upload from being acknowledged as published.
     */
    suspend fun exportForRecoveryAtRevision(): Result<RecoveryExport> = mutex.withLock {
        loadLocked().map { RecoveryExport(it.encode(), revision) }
    }

    /**
     * Merges a recovered keyring into this device's, then persists.
     *
     * UNION, never replacement. Local entries always survive; remote entries the
     * device lacks are added; an entry present on both must carry identical root
     * material or the whole import fails - see [HistoryKeyringMerge].
     *
     * Nothing here mints or rotates a root. Recovery brings roots that already
     * exist; creating one would produce material no archive was ever sealed under
     * and would defeat the point of recovering.
     *
     * The merged result is persisted through the normal path, so it is sealed
     * with THIS account's MK and its cache is written bound to THIS account.
     * Imported material is therefore re-bound at rest rather than trusted as it
     * arrived, and a blob that opened under another account can never be stored
     * as this one's.
     */
    suspend fun importFromRecovery(remoteKeyringBytes: ByteArray): Result<HistoryKeyring> =
        mutex.withLock {
            if (!feature.isEnabled()) return Result.failure(HistoryArchiveDisabledException())
            val remote = HistoryKeyring.decode(remoteKeyringBytes)
                .getOrElse { return Result.failure(it) }
            val local = loadLocked().getOrElse { return Result.failure(it) }

            val merged = HistoryKeyringMerge.union(local, remote)
                .getOrElse { return Result.failure(it) }

            // Nothing new to write: skip the seal/store round trip entirely so a
            // no-op recovery cannot fail on a locked vault.
            if (merged.entries.size == local.entries.size) {
                rememberOpened(merged)
                return Result.success(merged)
            }
            persistLocked(merged).map { merged }
        }

    /** The exact root a stored archive was sealed under, or null if this device does not hold it. */
    suspend fun find(chatId: String, rootVersion: Int): Result<HistoryRootEntry?> = mutex.withLock {
        loadLocked().map { it.find(chatId, rootVersion) }
    }

    /**
     * Drops the opened copy. Called when the vault session ends; the sealed blob on disk is
     * untouched, so the next [load] simply reopens it.
     */
    /**
     * Destroys every local trace of this account's history keyring because the
     * master key that sealed it is being replaced.
     *
     * DESTRUCTIVE AND EXPLICIT. Nothing calls this automatically. It is reachable
     * only from a user-confirmed E2EE reset, because it discards the roots that
     * open already-archived history: after this, archives sealed under the old
     * generation can never be opened again on this device.
     *
     * Deliberately NOT feature-flag gated. The flag exists to stop the feature
     * mutating state on its own; this is the opposite situation - a person has
     * explicitly asked for the material to be destroyed, and leaving unopenable
     * remnants behind because a flag is off would be worse than removing them.
     * It performs no network I/O, so flag containment of recovery traffic is
     * unaffected.
     *
     * All three slots go together. Leaving the marker or the cache behind would
     * present the next load with a keyring that disagrees with itself.
     */
    suspend fun discardForMkReplacement(): Result<Unit> = mutex.withLock {
        val failures = mutableListOf<Throwable>()
        // ORDER MATTERS, and the marker goes FIRST.
        //
        // These are three separate durable writes and a crash can land between
        // any two. The old order deleted the authoritative copy first, which left
        // the cache and the marker still agreeing with each other - so the next
        // cold start trusted the cache and served the OLD generation's roots
        // under the replacement key, silently undoing the reset.
        //
        // Removing the marker first makes every intermediate state fail closed:
        // the cache can no longer be validated, so the load falls through to the
        // authoritative copy, which cannot be opened by the replacement key and
        // is reported as a failure rather than as an empty or stale keyring.
        // Only when all three are gone does a load legitimately see "no keyring".
        store.deleteHistoryKeyringGeneration().onFailure { failures += it }
        store.deleteHistoryKeyringCache().onFailure { failures += it }
        store.deleteHistoryKeyring().onFailure { failures += it }
        cached = null
        cachedOwner = null
        rotationRequired.clear()
        // The revision counter is in-memory and per-process; it is not reset, so a
        // publisher that observed a pre-reset revision still sees a change.
        return if (failures.isEmpty()) {
            Result.success(Unit)
        } else {
            Result.failure(
                IllegalStateException(
                    "history keyring could not be fully discarded for MK replacement: " +
                        failures.joinToString { it.message ?: it::class.java.simpleName }
                )
            )
        }
    }

    fun clearCache() {
        cached = null
        cachedOwner = null
    }

    private suspend fun addVersionLocked(
        keyring: HistoryKeyring,
        chatId: String,
        version: Int,
    ): Result<HistoryRootEntry> {
        val entry = HistoryRootEntry(chatId, version, HistoryCrypto.newHistoryRoot())
        val updated = HistoryKeyring.of(keyring.entries + entry)
            .getOrElse { return Result.failure(it) }
        return persistLocked(updated).map { entry }
    }

    /**
     * Seal, store authoritatively, then refresh the cache, then publish.
     *
     * The order is deliberate. The MK-sealed copy goes first because it is the source of truth: if
     * the cache were written first and the authoritative write then failed, a cold start would
     * serve a root that has no recovery copy behind it. The in-memory cache is updated last, so a
     * failed write can never leave this process using a root that is not on disk.
     *
     * Note the consequence: minting or rotating a root requires an unlocked vault, because sealing
     * needs MK. READING archived history does not - that is what the Keystore cache is for. A chat
     * whose first archive is attempted while the vault is locked simply is not archived, and the
     * message is unaffected.
     */
    private suspend fun persistLocked(keyring: HistoryKeyring): Result<Unit> {
        val plain = keyring.encode()
        try {
            val sealed = vault.sealHistoryKeyring(plain).getOrElse { return Result.failure(it) }

            // ORDER, and the reason for it. Three durable writes, and no two of
            // them can be made atomic, so the order has to make every interruption
            // point recoverable rather than merely unlikely:
            //
            //   1. bump the marker   - invalidates the cache BEFORE it goes stale
            //   2. authoritative     - the source of truth advances
            //   3. cache, stamped    - re-validates the cache against the marker
            //
            // Crash after 1: cache stamp != marker, so the next load ignores the
            // cache and reads through the vault - the authoritative copy, old or
            // new, is what wins, and the load re-stamps the cache from it.
            // Crash after 2: identical handling, and the authoritative copy is
            // already the NEW state, which is exactly the case that used to be
            // shadowed by a stale cache.
            // Crash after 3: everything agrees.
            //
            // The marker is never rolled back on failure. A marker that ran ahead
            // costs one extra vault read; a marker that lagged would re-validate a
            // stale cache, which is the whole defect.
            val nextGeneration = (store.loadHistoryKeyringGeneration().getOrNull() ?: 0L) + 1
            store.saveHistoryKeyringGeneration(nextGeneration).getOrElse { return Result.failure(it) }
            store.saveHistoryKeyring(sealed).getOrElse { return Result.failure(it) }
            writeCache(plain, nextGeneration).getOrElse { return Result.failure(it) }
        } finally {
            HistoryCrypto.bestEffortWipe(plain)
        }
        rememberOpened(keyring)
        revision++
        return Result.success(Unit)
    }
}
