package com.messenger.app.data.encryption

import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Cross-platform MLS interop: can BouncyCastle (Android) read what mlspp
 * (Windows) produced?
 *
 * The fixtures in androidTest/assets are generated by the Windows client:
 *   cd windows_app/build && E2EE_MLS_EXPORT=<dir> ./messenger_app.exe
 * then copied into assets. They are real wire bytes, not synthetic.
 *
 * This is the test that catches a suite or framing mismatch between the two
 * implementations — nothing else in the suite exercises both libraries together.
 */
@RunWith(AndroidJUnit4::class)
class MlsInteropTest {

    private fun asset(name: String): ByteArray {
        val ctx = InstrumentationRegistry.getInstrumentation().context
        val hex = ctx.assets.open(name).bufferedReader().use { it.readText() }.trim()
        return E2ECrypto.fromHex(hex)!!
    }

    /**
     * A KeyPackage minted by mlspp must parse AND verify its own signature under
     * BouncyCastle. Signature verification is the strict part: it means both
     * sides agree on the suite, the LeafNode encoding, and the signing transcript.
     */
    @Test
    fun bouncyCastleParsesAndVerifiesMlsppKeyPackage() {
        val kp = MlsGroupCrypto.decodeKeyPackage(asset("win_keypackage.hex"))
        assertNotNull(kp)
        assertEquals(
            "cipher suite must match across platforms",
            MlsGroupCrypto.SUITE_ID, kp.suite.suiteID
        )
        assertTrue("mlspp KeyPackage must verify under BouncyCastle", kp.verify())
    }

    /** An mlspp Welcome must decode as an MLS message with a welcome body. */
    @Test
    fun bouncyCastleDecodesMlsppWelcome() {
        val msg = MlsGroupCrypto.decode(asset("win_welcome.hex"))
        assertNotNull("welcome must decode as an MLSMessage", msg)
        assertNotNull("MLSMessage must carry a welcome body", msg.welcome)
    }

    /** An mlspp commit must decode under BouncyCastle. */
    @Test
    fun bouncyCastleDecodesMlsppCommit() {
        val msg = MlsGroupCrypto.decode(asset("win_commit.hex"))
        assertNotNull("commit must decode as an MLSMessage", msg)
    }

    /**
     * An mlspp application message must decode. It should NOT be decryptable
     * without the group state — this asserts the framing is shared while the
     * secrets are not.
     */
    @Test
    fun bouncyCastleDecodesMlsppApplicationMessage() {
        val msg = MlsGroupCrypto.decode(asset("win_appmsg.hex"))
        assertNotNull("application message must decode as an MLSMessage", msg)
    }
}
